[package]
name = "vcl_derives"
version = "0.1.0"
authors = ["ying32(不在乎y)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[dependencies]
syn = "1.0.1"
quote = "1"
#proc-macro2 = "1"